<div class="buttons-set new-request-return-btn">
    <p class="back-link"><a href="<?php echo $block->getBackUrl(); ?>"><small>&laquo; </small>
            <?php echo $block->escapeHtml(__('Back')) ?></a></p>
    <button type="button" onclick="window.location='<?php echo $block->getNewRequestUrl() ?>';" class="action primary newrequestrma">
        <span><span><?php echo $block->escapeHtml(__('New request for return')) ?></span></span></button>

</div>
<?php $_rmas = $block->getRmas(); ?>
<?php if ($_rmas && count($_rmas)): ?>
    <div class="table-wrapper rma-history">
        <table class="data table table-rma-items history" id="my-rma-table">
            <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('Rmas') ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?php /* @escapeNotVerified */ echo __('ID') ?></th>
                    <th scope="col" class="col orderid"><?php /* @escapeNotVerified */ echo __('Order ID') ?></th>
                    <th scope="col" class="col status"><?php /* @escapeNotVerified */ echo __('Status') ?></th>
                    <th scope="col" class="col date"><?php /* @escapeNotVerified */ echo __('Date') ?></th>
                    <th scope="col" class="col view"><?php /* @escapeNotVerified */ echo __('Action') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_rmas as $_rma):
                    $rmaDate = ($_rma->getCreatedAt()) ? date('M d, Y', strtotime($_rma->getCreatedAt())) : 'N / A';
                    ?>
                    <tr>
                        <td data-th="<?php echo $block->escapeHtml(__('ID')) ?>" class="col id"><?php /* @escapeNotVerified */ echo $_rma->getId() ?></td>
                        <td data-th="<?php echo $block->escapeHtml(__('Order ID')) ?>" class="col order_id"><?php /* @escapeNotVerified */ echo $block->getOrderDetails($_rma->getOrderId()); ?></td>
                        <td data-th="<?php echo $block->escapeHtml(__('Status')) ?>" class="col status"><?php /* @escapeNotVerified */ echo $block->getStatusOptionText($_rma->getAdminstatus()) ?></td>
                        <td data-th="<?php echo $block->escapeHtml(__('Date')) ?>" class="col date"><?php /* @escapeNotVerified */ echo $rmaDate ?></td>
                        <td data-th="<?php echo $block->escapeHtml(__('View')) ?>" class="col date">
                            <a href="<?php /* @escapeNotVerified */ echo $block->getRmaRequestUrl().'rma_id/'.$_rma->getId(); ?>">View</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="seller-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?php /* @escapeNotVerified */ echo __('You have placed no Rmas.'); ?></span></div>
<?php endif ?>
    
<style>
    .buttons-set .back-link {
        float: left;
        margin: 0;
        line-height: 33px;
    }
    .buttons-set .newrequestrma {
        float: right;
    }
    .buttons-set {
        margin-bottom: 10px;
    }
</style>
    